name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          # Fail on any vulnerability severity (low, moderate, high, critical)
          fail-on-severity: low

          # Check all scopes including unknown (catches more edge cases)
          fail-on-scopes: runtime, unknown, development

          # Comment on the PR with vulnerability details
          comment-summary-in-pr: always

          # Show vulnerabilities even if they don't meet fail criteria
          show-openssf-scorecard: true

          # Warn about incompatible licenses (optional)
          # deny-licenses: GPL-3.0, LGPL-2.0, LGPL-2.1

          # Enable retry with exponential backoff for API calls
          retry-on-snapshot-warnings: true

          # Allow specific known vulnerabilities if needed (by GHSA ID)
          # allow-ghsas: GHSA-xxxx-xxxx-xxxx
