name: OSV-Scanner
on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]

permissions:
  actions: read
  contents: read
  # Write permissions are required for uploading the SARIF file to
  # GitHub, see https://docs.github.com/en/code-security/security-advisories/permission-to-write-security-advisories.
  security-events: write

jobs:
  scan-pr:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2
