name: OSV-Scanner
on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  schedule:
    - cron: "25 13 * * 4"
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  # Write permissions are required for uploading the SARIF file to
  # GitHub, see https://docs.github.com/en/code-security/security-advisories/permission-to-write-security-advisories.
  security-events: write

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2.2.2
    with:
      scan-args: |-
        -r
        --skip-git
        ./
      results-file-name: results.sarif
      upload-results: true
    permissions:
      actions: read
      contents: read
      security-events: write

  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@v2.2.2
    with:
      scan-args: |-
        -r
        --skip-git
        ./
    permissions:
      actions: read
      contents: read
      security-events: write
